# Generated by Django 5.2 on 2025-04-25 17:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('accion', models.CharField(max_length=50)),
                ('detalles', models.JSONField(blank=True, null=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_administrador', to=settings.AUTH_USER_MODEL)),
                ('usuario_objetivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_objetivo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
