# Generated by Django 5.2 on 2025-05-08 21:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habito', '0007_alter_habito_options_habito_racha_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyProgress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('completado', models.BooleanField(default=False)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_progress', to='habito.habito')),
            ],
            options={
                'verbose_name_plural': 'Daily Progress',
                'db_table': 'daily_progress',
            },
        ),
    ]
