# Generated by Django 5.2 on 2025-05-12 19:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hydration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='hydrationreminder',
            options={'ordering': ['time']},
        ),
        migrations.AlterModelOptions(
            name='hydrationstats',
            options={'verbose_name_plural': 'Hydration Stats'},
        ),
        migrations.RemoveField(
            model_name='hydrationstats',
            name='id',
        ),
        migrations.AlterField(
            model_name='hydrationstats',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='hydration_stats', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
