# Generated by Django 5.2 on 2025-04-25 17:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=20)),
                ('categoria', models.CharField(blank=True, max_length=12, null=True)),
                ('tipo_habito', models.CharField(blank=True, max_length=12, null=True)),
                ('objetivo', models.IntegerField()),
                ('racha_actual', models.IntegerField(default=0)),
                ('racha_maxima', models.IntegerField(default=0)),
                ('color', models.CharField(blank=True, max_length=7, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
