# Generated by Django 5.2 on 2025-05-08 21:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('habito', '0007_alter_habito_options_habito_racha_record_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('horarios', models.JSONField()),
                ('silenciar_desde', models.TimeField(blank=True, null=True)),
                ('silenciar_hasta', models.TimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('habito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordatorios', to='habito.habito')),
            ],
        ),
    ]
