# Generated by Django 5.2 on 2025-05-07 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='habito',
            name='meta_unidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
