# Generated by Django 5.2 on 2025-05-07 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0003_alter_habito_categoria_alter_habito_frecuencia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='categoria',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habito',
            name='frecuencia',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habito',
            name='meta_unidad',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='habito',
            name='tipo_habito',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
