# Generated by Django 5.2 on 2025-05-08 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0004_alter_habito_categoria_alter_habito_frecuencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='actual',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='habito',
            name='completed_dates',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='habito',
            name='icono',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
