# Generated by Django 5.2 on 2025-05-08 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0005_habito_actual_habito_completed_dates_habito_icono'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='habito',
            name='racha_maxima',
        ),
    ]
