# Generated by Django 5.2 on 2025-05-08 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0006_remove_habito_racha_maxima'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='habito',
            options={'verbose_name': 'Hábito', 'verbose_name_plural': 'Hábitos'},
        ),
        migrations.AddField(
            model_name='habito',
            name='racha_record',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='habito',
            name='completed_dates',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='habito',
            name='frecuencia',
            field=models.CharField(default='diario', max_length=20),
        ),
        migrations.AlterField(
            model_name='habito',
            name='objetivo',
            field=models.IntegerField(default=1),
        ),
    ]
