# Generated by Django 5.2 on 2025-05-08 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0007_alter_habito_options_habito_racha_record_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='nombre',
            field=models.CharField(max_length=50),
        ),
    ]
