# Generated by Django 5.2 on 2025-05-12 21:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0008_alter_habito_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='habito',
            name='last_reset',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
