# Generated by Django 5.2 on 2025-05-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('habito', '0009_habito_last_reset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='habito',
            name='last_reset',
            field=models.DateField(auto_now=True),
        ),
    ]
